<?php

namespace Mfpe\ReferencielBundle\Repository;

use Mfpe\ConfigBundle\Repository\AbstractRepository;
use Mfpe\ReferencielBundle\Entity\Refzonemarine;
use Mfpe\ReferencielBundle\Entity\RefGouvernorat;


/**
 * ReferencielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferencielRepository extends AbstractRepository
{
    public function getbydate($date)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->leftJoin('MfpeReferencielBundle:Refecheance', 'ech')
            ->Where('referenciel.id = ech.id')
            ->leftJoin('ech.previsions', 'p')
            ->getQuery()
            ->getResult();
        return $qb;
    }

    public function findregion($region)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->leftJoin('MfpeReferencielBundle:Region', 'reg')
            ->Where('referenciel.id = reg.id')
            ->where('UPPER(referenciel.nom) = UPPER(:region)')
            ->setParameter("region", UPPER($region))
            ->getQuery()
            ->getResult();
        return $qb;
    }

    public function search($intituleFr, $intituleAr, $categorie, $order = 'desc', $limit = 10, $page = 0)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->orderBy('referenciel.id', $order);
        if ($intituleFr) {
            $qb
                ->where('referenciel.intituleFr LIKE :intituleFr')
                ->setParameter('intituleFr', "%{$intituleFr}%");
        }
        if ($intituleAr) {
            $qb
                ->orWhere('referenciel.intituleAr LIKE :intituleAr')
                ->setParameter('intituleAr', "%{$intituleAr}%");
        }
        if ($categorie) {
            $qb->join('MfpeReferencielBundle:' . $categorie, 'c')
                ->andWhere('referenciel.id = c.id');
        }
        return $this->paginate($qb, $limit, $page);
    }

    public function finddelgationbyname($name)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->leftJoin('MfpeReferencielBundle:Refdelegation', 'del')
            ->Where('referenciel.id = del.id')
            ->andwhere('upper(referenciel.intituleFr) = upper(:name)')
            ->setParameter("name", $name)
            ->getQuery()
            ->getOneOrNullResult();
        return $qb;
    }

    public function findpaysmondebyname($name)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->leftJoin('MfpeReferencielBundle:Refpaysmonde', 'pay')
            ->Where('referenciel.id = pay.id')
            ->andwhere('upper(referenciel.intituleFr) = upper(:name)')
            ->setParameter("name", $name)
            ->getQuery()
            ->getOneOrNullResult();
        return $qb;
    }

    public function getmorevisitedel()
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->leftJoin('MfpeReferencielBundle:Refdelegation', 'del')
            ->Where('referenciel.id = del.id')
            ->orderBy("del.nbvisite", "DESC");

        return $qb->getQuery()->getResult();
    }

    public function findstationbyname($name)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->leftJoin('MfpeReferencielBundle:RefRccstation', 'station')
            ->Where('referenciel.id = station.id')
            ->andwhere('upper(referenciel.intituleFr) = upper(:name)')
            ->setParameter("name", $name)
            ->getQuery()
            ->getResult();
        return $qb;
    }


    public function finddelgationbycode($code)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->leftJoin('MfpeReferencielBundle:Refdelegation', 'del')
            ->Where('referenciel.id = del.id')
            ->andwhere('del.code = :code')
            ->setParameter("code", $code)
            ->getQuery()
            ->getOneOrNullResult();
        return $qb;
    }

    public function OrderRefastronomiegouvernorat($lang)
    {
        $orderedBy = "del.intituleFr";
        if ($lang == 'ar') {
            $orderedBy = "del.intituleAr";
        }
//        }elseif($lang=='en'){
//            $orderedBy="del.intituleAn";
//        }


        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('referenciel')
            ->innerJoin('MfpeReferencielBundle:Refastronomiegouvernorat', 'del')
            ->Where('referenciel.id = del.id')
            ->orderBy($orderedBy, "ASC");

        return $qb->getQuery()->getResult();
    }


    public function findnbjoursbyprevision($prevision)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('del.intituleFr')
            ->leftJoin('MfpeReferencielBundle:Refnbjours', 'del')
            ->Where('referenciel.id = del.id')
            ->andwhere('del.typeprevision = :prevision')
            ->setParameter("prevision", $prevision)
            ->getQuery()
            ->getOneOrNullResult();
        return $qb;
    }

    public function findDelais()
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('del.nbreMois')
            ->leftJoin('MfpeReferencielBundle:RefDelais', 'del')
            ->Where('referenciel.id = del.id')
            ->orderBy('del.id', "DESC")
            ->getQuery()->getResult();
        return $qb;
    }

    public function getGouvernoratByIntitule($gouvernorat)
{
    $qb = $this
        ->createQueryBuilder('referenciel')
        ->select('refGouv.id,refGouv.intituleFr,refGouv.intituleAr')
        ->leftJoin('MfpeReferencielBundle:RefGouvernorat', 'refGouv')
        ->where('refGouv.intituleFr LIKE :gouvernorat')
        ->orWhere('refGouv.intituleAr LIKE  :gouvernorat')
        ->setParameter("gouvernorat", trim("%{$gouvernorat}%"))
        ->setMaxResults(1)
        ->getQuery()
        ->getResult();
    return $qb;

}

    public function getDelegationByIntitule($delegation)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('refGouv.id,refGouv.intituleFr,refGouv.intituleAr')
            ->leftJoin('MfpeReferencielBundle:RefGouvernorat', 'refGouv')
            ->where('refGouv.intituleFr LIKE :delegation')
            ->orWhere('refGouv.intituleAr LIKE  :delegation')
            ->setParameter("delegation", trim("%{$delegation}%"))
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
        return $qb;
    }
    public function getSectorByIntitule($sector)
    {
        $qb = $this
            ->createQueryBuilder('referenciel')
            ->select('refGouv.id,refGouv.intituleFr,refGouv.intituleAr')
            ->leftJoin('MfpeReferencielBundle:RefGouvernorat', 'refGouv')
            ->where('refGouv.intituleFr LIKE :sector')
            ->orWhere('refGouv.intituleAr LIKE  :sector')
            ->setParameter("sector", trim("%{$sector}%"))
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
        return $qb;
    }


}
