services:
#    mfpe_collect_data.example:
#        class: Mfpe\CollectDataBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app_aneti_service:
        class: Mfpe\CollectDataBundle\Services\AnetiService
        arguments: [ '@service_container' ]

