imports:
    - { resource: parameters.yml }
    - { resource: parameters_mfpe.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MfpeConfigBundle/Resources/config/services.yml" }
    - { resource: "@MfpeAttestationBundle/Resources/config/services.yml" }
    - { resource: "@MfpeUniteRegionaleBundle/Resources/config/services.yml" }
    - { resource: "@MfpeCentreFormationBundle/Resources/config/services.yml" }
    - { resource: "@MfpeNotificationBundle/Resources/config/services.yml" }
    - { resource: "@MfpeCollectDataBundle/Resources/config/services.yml" }
    - { resource: "@MfpeDataSocioEconomicBundle/Resources/config/services.yml" }
    - { resource: "@MfpeEditiqueBundle/Resources/config/services.yml" }
    - { resource: "@MfpeHomeBundle/Resources/config/services.yml" }

parameters:
    locale: fr
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 9.4
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            filter_permissions:
                class: Mfpe\ConfigBundle\Services\DataPermissionsFilter
                enabled: true
        dql:
            datetime_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

lexik_jwt_authentication:

    secret_key:       '%jwt_private_key_path%' # required for token creation
    public_key:       '%jwt_public_key_path%'  # required for token verification
    pass_phrase:      '%jwt_key_pass_phrase%'  # required for token creation
    token_ttl:        '%jwt_token_ttl%'

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:  ["*"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "PATCH", "OPTIONS"]
        allow_headers: ["*"]
        max_age:       36000
    paths:
        '^/': ~

# Nelmio API Doc
nelmio_api_doc:

    documentation:
        host: '%host%'
        info:
            title: MFPE api
            description: MFPE api
            version: 1.0.0
        security:
            - Bearer: []
        accept_type:        "application/json"
        body_format:
            formats:        [ "json" ]
            default_format: "json"
        request_format:
            formats:
                json:       "application/json"
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header

    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)

sensio_framework_extra:
    view:    { annotations: true }
    request: { converters: true }

# FOS REST Bundle
fos_rest:
    routing_loader:
        default_format: json
        include_format: false #include format inside the route
    view:
        view_response_listener: force #force return entity directly from controller
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    param_fetcher_listener: true #convert the query params in the methods arguments
    exception:
        enabled: true
        #exception_controller: 'fos_rest.exception.controller:showAction'
        exception_controller: 'Mfpe\ConfigBundle\Controller\Exception\ExceptionController::showAction'
    serializer:
        groups: ['Default','PermissionGroup']
        serialize_null: true
    versioning:
        enabled: true
        default_version: '1.0'
        resolvers:
            query: true
            custom_header: true
            media_type:
                enabled: true
        guessing_order:
            - media_type
            - custom_header
            - query
    format_listener: #enable format listener to use mime type type
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json }
            - { path: '^/', priorities: ['json'], fallback_format: json }


jms_serializer:
    handlers:
        datetime:
            default_format: 'Y-m-d H:i'

white_october_tcpdf:
    tcpdf:
        k_title_magnification: 2

