# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
#parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false


    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    Mfpe\ConfigBundle\:
        resource: '../../src/Mfpe/ConfigBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        #exclude: '../../src/AppBundle/{Entity,Repository,Tests}'
        exclude: '../../src/Mfpe/ConfigBundle/{Repository,Tests}'

    Mfpe\ConfigBundle\Controller\:
        resource: '../../src/Mfpe/ConfigBundle/Controller'
        public: true
        tags: ['controller.service_arguments']


    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    Mfpe\ConfigBundle\Serializer\DoctrineEntityDeserializationSubscriber:
        tags: ['jms_serializer.event_subscriber']
        public: true


    # Injection des dependance dans le constructeur du controller SatelliteController
    # Dependances :
    #     - EntityMerger
    #     - ActivitePagination
    #     -
    Mfpe\ReferencielBundle\:
        resource: '../../src/Mfpe/ReferencielBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        #exclude: '../../src/AppBundle/{Entity,Repository,Tests}'
        exclude: '../../src/Mfpe/ReferencielBundle/{Repository,Tests}'

    Mfpe\ReferencielBundle\Controller\:
        resource: '../../src/Mfpe/ReferencielBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
    

    
