<?php

namespace Mfpe\AttestationBundle\Repository;

/**
 * ApplicationHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
