<?php

namespace Mfpe\AttestationBundle\Repository;

/**
 * DateExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateExamRepository extends \Doctrine\ORM\EntityRepository
{

}
