<?php

namespace Mfpe\AttestationBundle\Repository;

/**
 * DelaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelaisRepository extends \Doctrine\ORM\EntityRepository
{


}
