<?php

namespace Mfpe\AttestationBundle\Repository;

/**
 * HistoriqueStatutDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueStatutDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
