<?php

namespace Mfpe\AttestationBundle\Repository;

/**
 * StatutDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
