<?php

namespace Mfpe\CentreFormationBundle\Repository;

/**
 * CentreFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreFormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCentreFormations($data)
    {
        $query = $this->createQueryBuilder('CentreFormation');

        if (isset($data["gouvernorat"]) && !empty($data["gouvernorat"])) {
            $query->leftJoin('CentreFormation.gouvernorat', 'gouvernorat')
                ->andWhere('gouvernorat.code = :gouvernate')
                ->setParameter('gouvernate', $data["gouvernorat"]);
        }
        if (isset($data["delegation"]) && !empty($data["delegation"])) {
            $query->leftJoin('CentreFormation.delegation', 'delegation')
                ->andWhere('delegation.id = :delegation')
                ->setParameter('delegation', $data["delegation"]);
        }

        if (isset($data["secteur"]) && !empty($data["secteur"])) {
            $query->leftJoin('CentreFormation.specialiteCenters', 'specialiteCenters')
                ->andWhere('specialiteCenters.secteur = :sector')
                ->setParameter('sector', $data["secteur"]);
        }

        return $query->getQuery()->getResult();
    }
}
