<?php

namespace Mfpe\CentreFormationBundle\Repository;

/**
 * SpecialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSpecialities($data)
    {
        $query = $this->createQueryBuilder('Specialite');
        if (isset($data["secteur"]) && !empty($data["secteur"])) {
            //dd($data["secteur"]);
            $query->leftJoin('Specialite.secteur', 'secteur')
                ->andWhere('secteur.id = :sector')
                ->setParameter('sector', $data["secteur"]);
        }
        //dd($query->getQuery()->getSQL());
        //dd(count($query->getQuery()->getResult()));
        return $query->getQuery()->getResult();
    }
}
