<?php

namespace Mfpe\ConfigBundle\Repository;

/**
 * AbstractEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
