<?php

namespace Mfpe\ConfigBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{

    public function getRolesByStatus($status)
    {
        $qb = $this->createQueryBuilder('Role')
            ->where('Role.status LIKE :status')
            ->setParameter('status', '%' . $status . '%');
        return $qb->getQuery()->getResult();
    }


}
