<?php

namespace Mfpe\ReferencielBundle\DataFixtures\SecondDataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Faker;
//Entity

use Mfpe\CollectDataBundle\Entity\AnetiTable1;


class Aneti1Fixtures extends Fixture
{

    public function load(ObjectManager $manager)
    {


        //Tunis
        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2015");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("01-01-2015"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1151");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("NI");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("10");
        $aneti1->setDateAneti(new \DateTime("18-10-2016"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1152");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("NI");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("9");
        $aneti1->setDateAneti(new \DateTime("08-09-2017"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1151");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("NI");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("7");
        $aneti1->setDateAneti(new \DateTime("13-07-2017"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1152");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("NI");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("10");
        $aneti1->setDateAneti(new \DateTime("08-10-2019"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1151");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("NI");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        //Tunis
        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2015");
        $aneti1->setMois("9");
        $aneti1->setDateAneti(new \DateTime("11-09-2015"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1151");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Plins");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("12");
        $aneti1->setDateAneti(new \DateTime("28-12-2016"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1152");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Plins");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("5");
        $aneti1->setDateAneti(new \DateTime("30-05-2017"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1151");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Plins");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("8");
        $aneti1->setDateAneti(new \DateTime("13-08-2017"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1152");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Plins");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("06");
        $aneti1->setDateAneti(new \DateTime("02-06-2019"));
        $aneti1->setIdGouvernorat("11");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("1151");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Plins");
        $aneti1->setNombre("4");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        //Kasserine
        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Kasserine Nord"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("11");
        $aneti1->setDateAneti(new \DateTime("11-11-2019"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("1154");
        $aneti1->setLibDelegation("Kasserine Nord");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Nouvelles offres");
        $aneti1->setNombre("5");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Foussana"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("12");
        $aneti1->setDateAneti(new \DateTime("08-12-2019"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("1153");
        $aneti1->setLibDelegation("Foussana");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Nouvelles offres");
        $aneti1->setNombre("5");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sbiba"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("28-01-2018"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("1155");
        $aneti1->setLibDelegation("Sbiba");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Nouvelles offres");
        $aneti1->setNombre("5");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sbeïtla"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("2");
        $aneti1->setDateAneti(new \DateTime("06-02-2018"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("1156");
        $aneti1->setLibDelegation("Sbeïtla");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Nouvelles offres");
        $aneti1->setNombre("5");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sbiba"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("30-03-2018"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("1155");
        $aneti1->setLibDelegation("Sbiba");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Nouvelles offres");
        $aneti1->setNombre("5");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        //Sfax
        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Sfax"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Mahrès"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("4");
        $aneti1->setDateAneti(new \DateTime("01-04-2018"));
        $aneti1->setIdGouvernorat("13");
        $aneti1->setLibGouvernorat("Sfax");
        $aneti1->setIdDelegation("1157");
        $aneti1->setLibDelegation("Mahrès");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("RI");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Sfax"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sfax Ville"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("10");
        $aneti1->setDateAneti(new \DateTime("08-10-2016"));
        $aneti1->setIdGouvernorat("13");
        $aneti1->setLibGouvernorat("Sfax");
        $aneti1->setIdDelegation("1158");
        $aneti1->setLibDelegation("Sfax Ville");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("RI");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Sfax"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Mahrès"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("9");
        $aneti1->setDateAneti(new \DateTime("08-09-2017"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Sfax");
        $aneti1->setIdDelegation("1157");
        $aneti1->setLibDelegation("Mahrès");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("RI");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Sfax"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sfax Ville"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("12");
        $aneti1->setDateAneti(new \DateTime("08-12-2018"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Sfax");
        $aneti1->setIdDelegation("1158");
        $aneti1->setLibDelegation("Sfax Ville");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("RI");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Sfax"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Mahrès"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("9");
        $aneti1->setDateAneti(new \DateTime("08-09-2017"));
        $aneti1->setIdGouvernorat("12");
        $aneti1->setLibGouvernorat("Sfax");
        $aneti1->setIdDelegation("1157");
        $aneti1->setLibDelegation("Mahrès");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("RI");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        //Tozeur
        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tozeur"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Degache"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2015");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("01-01-2015"));
        $aneti1->setIdGouvernorat("14");
        $aneti1->setLibGouvernorat("Tozeur");
        $aneti1->setIdDelegation("1159");
        $aneti1->setLibDelegation("Degache");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CIVP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tozeur"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Nefta"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("11");
        $aneti1->setDateAneti(new \DateTime("28-11-2017"));
        $aneti1->setIdGouvernorat("14");
        $aneti1->setLibGouvernorat("Tozeur");
        $aneti1->setIdDelegation("1160");
        $aneti1->setLibDelegation("Nefta");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CIVP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);


        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tozeur"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Degache"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2020");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("01-03-2020"));
        $aneti1->setIdGouvernorat("14");
        $aneti1->setLibGouvernorat("Tozeur");
        $aneti1->setIdDelegation("1159");
        $aneti1->setLibDelegation("Degache");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CIVP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tozeur"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Nefta"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("7");
        $aneti1->setDateAneti(new \DateTime("05-07-2016"));
        $aneti1->setIdGouvernorat("14");
        $aneti1->setLibGouvernorat("Tozeur");
        $aneti1->setIdDelegation("1160");
        $aneti1->setLibDelegation("Nefta");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CIVP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tozeur"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Degache"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2020");
        $aneti1->setMois("2");
        $aneti1->setDateAneti(new \DateTime("02-02-2020"));
        $aneti1->setIdGouvernorat("14");
        $aneti1->setLibGouvernorat("Tozeur");
        $aneti1->setIdDelegation("1159");
        $aneti1->setLibDelegation("Degache");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CIVP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();
        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tozeur"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Degache"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2020");
        $aneti1->setMois("2");
        $aneti1->setDateAneti(new \DateTime("02-02-2020"));
        $aneti1->setIdGouvernorat("14");
        $aneti1->setLibGouvernorat("Tozeur");
        $aneti1->setIdDelegation("1159");
        $aneti1->setLibDelegation("Degache");
        $aneti1->setBureau("1110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CIVP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CIVP Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("4");
        $aneti1->setDateAneti(new \DateTime("21-04-2018"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CIVP en cour");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("12");
        $aneti1->setDateAneti(new \DateTime("22-12-2017"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("SIVP Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2015");
        $aneti1->setMois("5");
        $aneti1->setDateAneti(new \DateTime("11-05-2015"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("220");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("SIVP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("SCV Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("SCV inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("5");
        $aneti1->setDateAneti(new \DateTime("02-05-2017"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("SCV en cour");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();


        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CAIP Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CAIP inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2020");
        $aneti1->setMois("2");
        $aneti1->setDateAneti(new \DateTime("11-02-2020"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CAIP en cour");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CIDES Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("23-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CIDES inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2020");
        $aneti1->setMois("5");
        $aneti1->setDateAneti(new \DateTime("31-05-2020"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("77");
        $aneti1->setLibBureau("BAB BHAR");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CIDES en cour");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();


        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("29");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("CARTHAGE");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CRVA Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Foussana"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("56");
        $aneti1->setLibDelegation("Foussana");
        $aneti1->setBureau("110");
        $aneti1->setLibBureau("Foussana");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("CRVA inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Foussana"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2019");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2019"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("56");
        $aneti1->setLibDelegation("Foussana");
        $aneti1->setBureau("77");
        $aneti1->setLibBureau("Foussana");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("CRVA en cour");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Foussana"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("6");
        $aneti1->setDateAneti(new \DateTime("02-06-2018"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("56");
        $aneti1->setLibDelegation("Foussana");
        $aneti1->setBureau("77");
        $aneti1->setLibBureau("Foussana");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Forsati Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
            $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sbiba"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2018");
        $aneti1->setMois("6");
        $aneti1->setDateAneti(new \DateTime("02-06-2018"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("57");
        $aneti1->setLibDelegation("Sbiba");
        $aneti1->setBureau("54");
        $aneti1->setLibBureau("Sbiba");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Forsati Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sbiba"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("10");
        $aneti1->setDateAneti(new \DateTime("02-10-2017"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("57");
        $aneti1->setLibDelegation("Sbiba");
        $aneti1->setBureau("54");
        $aneti1->setLibBureau("Sbiba");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Forsati en cour");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sbiba"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("2");
        $aneti1->setDateAneti(new \DateTime("02-02-2017"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("57");
        $aneti1->setLibDelegation("Sbiba");
        $aneti1->setBureau("54");
        $aneti1->setLibBureau("Sbiba");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Forsati acheves");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Kasserine"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Sbiba"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("2");
        $aneti1->setDateAneti(new \DateTime("02-02-2017"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Kasserine");
        $aneti1->setIdDelegation("57");
        $aneti1->setLibDelegation("Sbiba");
        $aneti1->setBureau("54");
        $aneti1->setLibBureau("Sbiba");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("KARAMA Nouv");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("02-03-2016"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("KARAMA en cour");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("02-03-2016"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("KARAMA acheves");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("02-03-2016"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("530");
        $aneti1->setLibBureau("Bab El Bhar");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("KARAMA inser");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2015");
        $aneti1->setMois("9");
        $aneti1->setDateAneti(new \DateTime("02-09-2015"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("ME etudies");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2012");
        $aneti1->setMois("1");
        $aneti1->setDateAneti(new \DateTime("02-01-2012"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("ME finances");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("02-03-2016"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("ME BA");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2013");
        $aneti1->setMois("12");
        $aneti1->setDateAneti(new \DateTime("02-12-2013"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Bab el bhar");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("ME Visite");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2017");
        $aneti1->setMois("7");
        $aneti1->setDateAneti(new \DateTime("02-07-2017"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Action ME SI");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("02-03-2016"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("H");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Action ME CEFE");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Bab-El-Bhar"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2016");
        $aneti1->setMois("3");
        $aneti1->setDateAneti(new \DateTime("02-03-2016"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("53");
        $aneti1->setLibDelegation("Bab-El-Bhar");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Bab el bhar");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("0");
        $aneti1->setIndicateur("Action ME CREE");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();

        $aneti1 = new AnetiTable1();
        $gouvernorat = $manager->getRepository('MfpeReferencielBundle:RefGouvernorat')->findOneBy(array("intituleFr" => "Tunis"));
        $aneti1->setGouvernorat($gouvernorat);
        $delegation = $manager->getRepository('MfpeReferencielBundle:RefDelegation')->findOneBy(array("intituleFr" => "Carthage"));
        $aneti1->setDelegation($delegation);
        $aneti1->setAnnee("2011");
        $aneti1->setMois("8");
        $aneti1->setDateAneti(new \DateTime("02-08-2011"));
        $aneti1->setIdGouvernorat("37");
        $aneti1->setLibGouvernorat("Tunis");
        $aneti1->setIdDelegation("54");
        $aneti1->setLibDelegation("Carthage");
        $aneti1->setBureau("540");
        $aneti1->setLibBureau("Carthage");
        $aneti1->setGenre("F");
        $aneti1->setDipSup("1");
        $aneti1->setIndicateur("Action ME Morraine");
        $aneti1->setNombre("1");
        $aneti1->setEnable("true");
        $manager->persist($aneti1);
        $manager->flush();
    }



}