<?php

namespace Mfpe\UniteRegionaleBundle\Repository;

/**
 * CadresRegionauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadresRegionauxRepository extends \Doctrine\ORM\EntityRepository
{
}
