<?php

namespace Mfpe\UniteRegionaleBundle\Repository;

/**
 * DescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDescription($identiteRegion)
    {
        $query = $this->createQueryBuilder('Description');
        $query->leftJoin('Description.identiteRegion', 'identiteRegion');
        $query->Where('identiteRegion = :identiteRegion')
            ->setParameter('identiteRegion', $identiteRegion);

        return $query->getQuery()->getResult();
    }

}
