<?php

namespace Mfpe\UniteRegionaleBundle\Repository;

/**
 * UniteRegionaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteRegionaleRepository extends \Doctrine\ORM\EntityRepository
{
}
