<?php

namespace Mfpe\CollectDataBundle\Repository;

/**
 * AnetiTable2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnetiTable2Repository extends \Doctrine\ORM\EntityRepository
{
    public function findDataEmploiTable2ByFiltre($data)
    {

        $query = $this->createQueryBuilder('AnetiTable2');

        if (isset($data["governorate"]) && !empty($data["governorate"])) {
            $governorat = trim(($data["governorate"]));
            $query->leftJoin('AnetiTable2.gouvernorat', 'gouvernorat');
            $query
                ->andwhere('gouvernorat.id = :gouvernate')
                //      ->orWhere('gouvernorat.code = :gouvernate')
                ->setParameter('gouvernate', $governorat);
        }
        if (isset($data["delegation"]) && !empty($data["delegation"])) {
            $delegation = trim(intval($data["delegation"]));
            $query->leftJoin('AnetiTable2.delegation', 'delegation');
            $query
                ->andwhere('delegation.id = :delegation')
                ->setParameter('delegation', $delegation);
        }
        if (isset($data["bureau_emploi"]) && !empty($data["bureau_emploi"])) {
            $bureauEmploi = strtoupper($data["bureau_emploi"]);

            $query
                ->andWhere('UPPER(AnetiTable2.libBureau) LIKE :bureau')
                ->setParameter('bureau', "%{$bureauEmploi}%");

        }

        if (isset($data["from"]) && !empty($data["from"]) && isset($data["to"]) && !empty($data["to"])) {
            $du = date("Y-m-d H:i:s", strtotime($data["from"]));
            $au = date("Y-m-d H:i:s", strtotime($data["to"]));

            $query->andWhere("AnetiTable2.dateAneti > :du")
                ->andWhere("AnetiTable2.dateAneti < :au")
                ->setParameter('du', $du)
                ->setParameter('au', $au);
        }

        return $query->getQuery()->getResult();
    }
    public function findDataEmploiTable2ByFiltreP2($data)
    {
        $query = $this->createQueryBuilder('AnetiTable2');

        if (isset($data["governorate"]) && !empty($data["governorate"])) {
            $governorat = trim(($data["governorate"]));
            $query->leftJoin('AnetiTable2.gouvernorat', 'gouvernorat');
            $query
                ->andwhere('gouvernorat.id = :gouvernate')
                //      ->orWhere('gouvernorat.code = :gouvernate')
                ->setParameter('gouvernate', $governorat);
        }
        if (isset($data["delegation"]) && !empty($data["delegation"])) {
            $delegation = trim(intval($data["delegation"]));
            $query->leftJoin('AnetiTable2.delegation', 'delegation');
            $query
                ->andwhere('delegation.id = :delegation')
                ->setParameter('delegation', $delegation);
        }
        if (isset($data["bureau_emploi"]) && !empty($data["bureau_emploi"])) {
            $bureauEmploi = strtoupper($data["bureau_emploi"]);

            $query
                ->andWhere('UPPER(AnetiTable2.libBureau) LIKE :bureau')
                ->setParameter('bureau', "%{$bureauEmploi}%");

        }

        if (isset($data["fromSecondary"]) && !empty($data["fromSecondary"]) && isset($data["toSecondary"]) && !empty($data["toSecondary"])) {
            $du = date("Y-m-d H:i:s", strtotime($data["from"]));
            $au = date("Y-m-d H:i:s", strtotime($data["to"]));

            $query->andWhere("AnetiTable2.dateAneti > :du")
                ->andWhere("AnetiTable2.dateAneti < :au")
                ->setParameter('du', $du)
                ->setParameter('au', $au);
        }

        return $query->getQuery()->getResult();
    }
    public function getNationalDataEmploiP2($data)
    {
        $query = $this->createQueryBuilder('AnetiTable2');
        $query->select("AnetiTable2");
        if (isset($data["bureau_emploi"]) && !empty($data["bureau_emploi"])) {
            $bureauEmploi = strtoupper($data["bureau_emploi"]);
            $query
                ->andWhere('UPPER(AnetiTable2.libBureau) LIKE :bureau')
                ->setParameter('bureau', "%{$bureauEmploi}%");

        }
        if (isset($data["fromSecondary"]) && !empty($data["fromSecondary"]) && isset($data["toSecondary"]) && !empty($data["toSecondary"])) {
            $du = date("Y-m-d H:i:s", strtotime($data["fromSecondary"]));
            $au = date("Y-m-d H:i:s", strtotime($data["toSecondary"]));
            $query->andWhere("AnetiTable2.dateAneti > :du")
                ->andWhere("AnetiTable2.dateAneti < :au")
                ->setParameter('du', $du)
                ->setParameter('au', $au);
        }
        return $query->getQuery()->getResult();
    }
}
