<?php

namespace Mfpe\CollectDataBundle\Repository;

/**
 * ProjectDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectDataRepository extends \Doctrine\ORM\EntityRepository
{



    public function findNumberProject($gouvernorat, $type)
    {
        $query = $this->createQueryBuilder('ProjectData')
               ->select('COUNT(ProjectData.id)');
        $query->leftJoin('ProjectData.governorat', 'governorat');

        if (isset($gouvernorat)) {
            $query
                ->andWhere('ProjectData.governorat = :gouvernate')
                ->setParameter('gouvernate', $gouvernorat);
        }

        if (isset($type)) {
            $query
                ->andWhere('ProjectData.type = :type')
                ->setParameter('type', $type);
                //->orderBy('ProjectData.updatedAt', "DESC");
        }
        return $query->getQuery()->getSingleScalarResult();

    }
}
